# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'HQSwiftFirstTime' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FFBaseFramework

  pod 'Alamofire', '~> 4.7.3'
  pod 'SnapKit', '~> 4.2.0'
  pod 'SwiftyJSON', '~> 4.2.0'

end
